service: prisma-aws-lambda-example
plugins:
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  region: us-east-1
  runtime: nodejs14.x
  timeout: 10

functions:

  authorize:
    handler: functions/authorize.handler

  status:
    handler: functions/status.handler
    events:
      - http:
          method: GET
          path: /
  seed:
    handler: functions/seed.handler
    events:
      - http:
          method: GET
          path: /seed
          cors: true

  login:
    handler: functions/auth/login.handler
    events:
      - http:
          method: POST
          path: /login
          cors: true

  getUsers:
    handler: functions/user/list.handler
    events:
      - http:
          method: GET
          path: /users
          authorizer: authorize
          cors: true
  createUser:
    handler: functions/user/create-user.handler
    events:
      - http:
          method: POST
          path: /users
          cors: true
  updateUser:
    handler: functions/user/update.handler
    events:
      - http:
          method: PUT
          path: /users/{id}
          authorizer: authorize
          cors: true
  deleteUser:
    handler: functions/user/delete.handler
    events:
      - http:
          method: DELETE
          path: /users/{id}
          authorizer: authorize
          cors: true

  createBank:
    handler: functions/bank/create.handler
    events:
      - http:
          method: POST
          path: /bank
          authorizer: authorize
          cors: true
  listBank:
    handler: functions/bank/list.handler
    events:
      - http:
          method: GET
          path: /bank
          authorizer: authorize
          cors: true
  getBankById:
    handler: functions/bank/getById.handler
    events:
      - http:
          method: GET
          path: /bank/{id}
          authorizer: authorize
          cors: true
  deleteBank:
    handler: functions/bank/delete.handler
    events:
      - http:
          method: DELETE
          path: /bank/{id}
          authorizer: authorize
          cors: true

# only include the Prisma binary required on AWS Lambda while packaging
package:
  patterns:
    - '!node_modules/.prisma/client/libquery_engine-*'
    - 'node_modules/.prisma/client/libquery_engine-rhel-*'
    - '!node_modules/prisma/libquery_engine-*'
    - '!node_modules/@prisma/engines/**'
